CLASS zcl_13_newyork_4263 DEFINITION INHERITING FROM zcl_11_citizen_4263
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_13_NEWYORK_4263 IMPLEMENTATION.
ENDCLASS.
