CLASS zcl_06_storage_4362 DEFINITION INHERITING FROM zcl_05_plant_4362
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_06_STORAGE_4362 IMPLEMENTATION.
ENDCLASS.
