CLASS zcl_19_honda_4362 DEFINITION ABSTRACT INHERITING FROM zcl_18_moto_4263
  PUBLIC
  "FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
   METHODS set_model ABSTRACT EXPORTING model type string.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_19_HONDA_4362 IMPLEMENTATION.
ENDCLASS.
