CLASS zcl_08_leon_4362 DEFINITION INHERITING FROM zcl_07_animal_4362
  PUBLIC

  CREATE PUBLIC .

  PUBLIC SECTION.
   METHODS walk REDEFINITION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_08_leon_4362 IMPLEMENTATION.
  METHOD walk.
    rv_walk = 'Lion walks'.
  ENDMETHOD.

ENDCLASS.
